// Product Types
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_LOADED = "GET_PRODUCTS_LOADED";
export const UPDATE_PRODUCT_EDITING = "UPDATE_PRODUCT_EDITING";

// Auth Types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// User Types
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_LOADED = "GET_USERS_LOADED";
export const UPDATE_USER_EDITING = "UPDATE_USER_EDITING";

// Error Types
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
